#------------------------------------------------------------------------------
# Makefile for Assignment 1
#
# make                   makes httpserver
# make clean             cleans out all binaries created from make
#------------------------------------------------------------------------------

httpserver : httpserver.c
	gcc -std=c11 -Wall -Wextra -Wpedantic -Wshadow -o httpserver httpserver.c

clean :
	rm -f httpserver
